apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: reporting-cron-job
spec:
  schedule: "0 0 3 * *"
  jobTemplate:
    completions: 3
    parallelism: 3
    template:
      spec:
        containers:
          - name: reporter
            image: reporting-tool
        restartPolicy: Never