# Default for namespace. Applies if not specified
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
spec:
  limits:
      # default limit for containers
    - default:
        cpu: 1
        memory: 512Mi
      # default requested resources for containers
      defaultRequest:
        cpu: 0.5
        memory: 256Mi
      min:
        cpu: 0.1
        memory: 1Mi
      max:
        cpu: 3
        memory: 1Gi
      type: Container