apiVersion: v1

kind: Pod

metadata:
  name: app-pod
  labels:
    app: myapp
    type: application

spec:
  # it's a POD security setup
  securityContext:
    runAsUser: non-root
  containers:
  - name: nginx-container
    image: nginx
    command: ["overrides default ENTRYPOINT instruction"]
    args: ["overrides default CMD instruction"]
    # Container security setup
    securityContext:
      runAsUser: non-root
      # Available only at this level
      capabilities:
        add: ["MAC_ADMIN"]
    ports:
      - containerPort: 3000
    resources:
      requests:
        memory: "256Mi"
        cpu: 1
      limits:
        memory: "1G" #terminate after cross this value
        cpu: 2
    env:
      - name: TMP_VAR
        value: "smth"
      #or value from map
      - name: APP_COLOR
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: APP_COLOR
      #or secret value from hashed secret
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: app-secret
            key: DB_USER
    envFrom:
      - configMapRef:
          #not a file itself
          name: app-config
      - secretRef:
          name: app-secret
    # or even volume
    volumes:
      - name: app-config-volume
        configMap:
          name: app-config
    tolerations:
      - key: "app"
        operator: "Equal"
        value: "blue"
        effect: "NoSchedule"


