apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 8080
      port: 8080 #port on the service
  selector:
    app: myapp
    type: back-end